spring:
  profiles:
    active: development
  data:
    r2dbc:
      repositories:
        enabled: true

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db_receipt
    username: postgres
    password: admin
    name: db_receipt
    pool:
      enabled: true
      max-size: 20


logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework.r2dbc: debug

server:
  port: 9090
#server.port=9090
#spring.r2dbc.name=db_receipt
#spring.r2dbc.url=r2dbc:postgresql://localhost:5432/db_receipt
#spring.r2dbc.username=postgres
#spring.r2dbc.password=admin
